version: '3.5'
# Other docker-compose examples in /examples

services:
  velocity1:
    image: itzg/bungeecord
    ports:
      - "25577:25577"
    volumes:
      - "/home/daniel/mcTest2/velocity1/server:/server"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/daniel/mcTest2/_templates/velocity/velocity.toml:/config/velocity.toml:ro"
    environment:
      TYPE: Velocity
    restart: unless-stopped
  paper1:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "/home/daniel/mcTest2/paper1/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/daniel/mcTest2/_templates/paper/ops.json:/config/ops.json:ro"
      - "/home/daniel/mcTest2/_templates/paper/spigot.yml:/config/spigot.yml:ro"
      - "/home/daniel/mcTest2/_templates/paper/whitelist.json:/config/whitelist.json:ro"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.8.8
      #VERSION: 1.16.4
      # needed for Paper versions before 1.14
      CONSOLE: "false"
      #TZ: Europe/Zurich
      ONLINE_MODE: "FALSE"
    restart: unless-stopped
  paper2:
    image: itzg/minecraft-server
    ports:
      - "25566:25565"
    volumes:
      - "/home/daniel/mcTest2/paper2/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/daniel/mcTest2/_templates/paper/ops.json:/config/ops.json:ro"
      - "/home/daniel/mcTest2/_templates/paper/spigot.yml:/config/spigot.yml:ro"
      - "/home/daniel/mcTest2/_templates/paper/whitelist.json:/config/whitelist.json:ro"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.8.8
      #VERSION: 1.16.4
      # needed for Paper versions before 1.14
      CONSOLE: "false"
      #TZ: Europe/Zurich
      ONLINE_MODE: "FALSE"
    restart: unless-stopped
  paper3:
    image: itzg/minecraft-server
    ports:
      - "25567:25565"
    volumes:
      - "/home/daniel/mcTest2/paper3/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/daniel/mcTest2/_templates/paper/ops.json:/config/ops.json:ro"
      - "/home/daniel/mcTest2/_templates/paper/spigot.yml:/config/spigot.yml:ro"
      - "/home/daniel/mcTest2/_templates/paper/whitelist.json:/config/whitelist.json:ro"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      #VERSION: 1.8.8
      VERSION: 1.16.4
      # needed for Paper versions before 1.14
      CONSOLE: "false"
      #TZ: Europe/Zurich
      ONLINE_MODE: "FALSE"
    restart: unless-stopped