version: '3.5'
# Other docker-compose examples in /examples

services:
  velocity1:
    image: itzg/bungeecord
    ports:
      - "25577:25577"
    volumes:
      - "/home/daniel/mcTest2/velocity1/server:/server"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      TYPE: Velocity
    restart: unless-stopped
  paper1:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "/home/daniel/mcTest2/paper1/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.8.8
      #VERSION: 1.16.4
      # needed for Paper versions before 1.14
      CONSOLE: "false"
      #TZ: Europe/Zurich
      ONLINE_MODE: "FALSE"
    restart: unless-stopped